const FETCH_USERS_LOADING = "FETCH_USERS_LOADING";
const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";

export { FETCH_USERS_ERROR, FETCH_USERS_LOADING, FETCH_USERS_SUCCESS };
